name: Postman CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Stripe Customers collection
        run: |
          newman run collections/customers/Customers.postman_collection.json -e environments/Stripe_API_env.postman_environment.json --env-var "secret_key=${{ secrets.STRIPE_SECRET_KEY }}"